<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <AssemblyName>LibraryTests</AssemblyName>
    <PackageId>LibraryTests</PackageId>
    <SignAssembly>false</SignAssembly>
    <AssemblyOriginatorKeyFile>../../SigningKey.snk</AssemblyOriginatorKeyFile>
    <SkipDefaultAdapters>true</SkipDefaultAdapters>
    <DisableSharedTestHost>true</DisableSharedTestHost>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
	<!--<DefineConstants>$(DefineConstants);LONG_RUNNING_TESTS</DefineConstants>-->
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="_Data\*" />
    <EmbeddedResource Include="_Data\*" />
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Include="ExFat\Environment\exFAT.vhdx.gz" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Utilities\DiscUtils.Diagnostics\DiscUtils.Diagnostics.csproj" />
    <ProjectReference Include="..\..\Library\DiscUtils.Core\DiscUtils.Core.csproj" />
    <ProjectReference Include="..\..\Library\DiscUtils\DiscUtils.csproj" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0'))">
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.*" />
	<PackageReference Include="xunit" Version="2.9.*" />
	<PackageReference Include="xunit.extensibility.core" Version="2.9.*" />
	<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  <PrivateAssets>all</PrivateAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="K4os.Compression.LZ4" Version="1.3.*" />
	<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.*" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.*" />
	<PackageReference Include="System.IO.Compression" Version="*" />
	<PackageReference Include="xunit" Version="2.9.*" />
	<PackageReference Include="xunit.extensibility.core" Version="2.9.*" />
	<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  <PrivateAssets>all</PrivateAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net5.0')) And $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net48'))">
    <PackageReference Include="K4os.Compression.LZ4" Version="1.3.*" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="System.IO.Compression" Version="*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net5.0'))">
    <PackageReference Include="K4os.Compression.LZ4" Version="1.3.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Swap\Data\" />
    <Folder Include="Wim\Data\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="plist.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
